//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSubscriptionDetail
    {
        public int AccountId { get; set; }
        public int AccountTypeId { get; set; }
        public int SubscriptionTypeId { get; set; }
        public decimal Price { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Modified { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountType AccountType { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }
    }
}
