//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubOrderDetail
    {
        public int SubOrderId { get; set; }
        public int ItemId { get; set; }
        public int OrderQuantity { get; set; }
        public string OrderType { get; set; }
        public string OrderPreferences { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
