//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaiterTable
    {
        public int AccountId { get; set; }
        public int BranchId { get; set; }
        public int WaiterId { get; set; }
        public int TableId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Table Table { get; set; }
        public virtual User User { get; set; }
    }
}
